#!/usr/bin/env ruby
# Adds MakeCodeBridgePlugin.swift and .m to the Xcode project generated by
# `npx cap add ios` so they get compiled into the app target.
#
# Run from the repo root after copying plugin files into:
#   ios/App/App/Plugins/MakeCodeBridge/
#
# Requires the `xcodeproj` gem:
#   gem install xcodeproj --no-document

require 'xcodeproj'

PROJECT_PATH = 'ios/App/App.xcodeproj'
PLUGIN_FILES  = %w[MakeCodeBridgePlugin.swift MakeCodeBridgePlugin.m].freeze

abort "ERROR: Xcode project not found at #{PROJECT_PATH}" unless Dir.exist?(PROJECT_PATH)

project = Xcodeproj::Project.open(PROJECT_PATH)

# Capacitor names the compile target "App"
app_target = project.native_targets.find { |t| t.name == 'App' }
abort 'ERROR: App target not found in Xcode project' unless app_target

# The source group is also named "App" and sits at ios/App/App/
app_group = project.main_group.children.find do |g|
  g.is_a?(Xcodeproj::Project::Object::PBXGroup) && g.display_name == 'App'
end
abort 'ERROR: App source group not found in project navigator' unless app_group

# Create Plugins/MakeCodeBridge groups if they don't already exist
plugins_group =
  app_group.children.find { |g| g.respond_to?(:display_name) && g.display_name == 'Plugins' } ||
  app_group.new_group('Plugins', 'Plugins')

bridge_group =
  plugins_group.children.find { |g| g.respond_to?(:display_name) && g.display_name == 'MakeCodeBridge' } ||
  plugins_group.new_group('MakeCodeBridge', 'MakeCodeBridge')

added = 0
PLUGIN_FILES.each do |filename|
  already_present = bridge_group.children.any? do |f|
    f.respond_to?(:display_name) && f.display_name == filename
  end

  if already_present
    puts "  = #{filename} (already in project)"
    next
  end

  file_ref = bridge_group.new_file(filename)
  app_target.add_file_references([file_ref])
  puts "  + #{filename}"
  added += 1
end

if added > 0
  project.save
  puts "Saved #{PROJECT_PATH} (#{added} file(s) added)"
else
  puts "No changes needed — files already registered"
end
